name: fastapi-playground
channels:
  - conda-forge
dependencies:
  - annotated-doc>=0.0.4
  - annotated-types>=0.7.0
  - anyio>=4.12.0
  - astroid>=4.0.3
  - async-timeout>=5.0.1
  - asyncpg>=0.31.0
  - backports.zstd>=1.3.0
  - brotli-python>=1.2.0
  - bzip2>=1.0.8
  - ca-certificates>=2026.1.4
  - certifi>=2026.1.4
  - charset-normalizer>=3.4.4
  - click>=8.3.1
  - colorama>=0.4.6
  - dill>=0.4.0
  - dnspython>=2.8.0
  - email-validator>=2.3.0
  - exceptiongroup>=1.3.1
  - expat>=2.7.3
  - fastapi>=0.128.0
  - fastapi-cli>=0.0.20
  - greenlet>=3.3.0
  - h11>=0.16.0
  - h2>=4.3.0
  - hpack>=4.1.0
  - httpcore>=1.0.9
  - httptools>=0.7.1
  - httpx>=0.28.1
  - hyperframe>=6.1.0
  - idna>=3.11
  - importlib-metadata>=8.7.0
  - iniconfig>=2.3.0
  - isort>=7.0.0
  - jinja2>=3.1.6
  - markdown-it-py>=4.0.0
  - markupsafe>=3.0.3
  - mccabe>=0.7.0
  - mdurl>=0.1.2
  - mypy>=1.19.1
  - mypy_extensions>=1.1.0
  - openssl>=3.6.0
  - packaging>=25.0
  - pathspec>=0.12.1
  - pip>=25.3
  - platformdirs>=4.5.1
  - pluggy>=1.6.0
  - psutil>=7.2.1
  - pydantic>=2.12.5
  - pydantic-core>=2.41.5
  - pydantic-extra-types>=2.11.0
  - pydantic-settings>=2.12.0
  - pygments>=2.19.2
  - pyhumps>=3.8.0
  - pylint>=4.0.4
  - pysocks>=1.7.1
  - pytest>=9.0.2
  - pytest-mock>=3.15.1
  - python>=3.12.12,<3.13
  - python-dotenv>=1.2.1
  - python-librt>=0.7.7
  - python-multipart>=0.0.21
  - pyyaml>=6.0.3
  - requests>=2.32.5
  - rich>=14.2.0
  - rich-toolkit>=0.17.1
  - setuptools>=80.9.0
  - shellingham>=1.5.4
  - sniffio>=1.3.1
  - sqlalchemy>=2.0.45
  - sqlmodel>=0.0.31
  - starlette>=0.50.0
  - tomli>=2.3.0
  - tomlkit>=0.13.3
  - typer>=0.21.0
  - typing-extensions>=4.15.0
  - typing-inspection>=0.4.2
  - tzdata>=2025c
  - urllib3>=2.6.2
  - uvicorn>=0.40.0
  - uvicorn-standard>=0.40.0
  - uvloop>=0.22.1
  - watchfiles>=1.1.1
  - websockets>=15.0.1
  - wheel>=0.45.1
  - zipp>=3.23.0
  - pip:
    - humps==0.2.2
    - types-PyYAML==6.0.12.20241230
    - types-ujson==5.10.0.20240515
